import { PatientBrief, PatientFullRecord, PatientDemographics, ClinicalEvidence } from '../types/clinical';
import { CaseSummary, DecisionResponse } from '../types/case';
import { CMSPolicyItem, PolicyLookupResponse } from '../types/policy';
import { CriterionStatus, PreCheckAssessment } from '../types/criteria';

export const MOCK_PATIENTS_BRIEF: PatientBrief[] = [
  {
    patient_id: 'MEM-948201',
    name: 'Eleanor Vance',
    birth_date: '1974-03-12',
    gender: 'female',
    mrn: 'MRN-784920',
    primary_physician: 'Dr. Sarah Lin, MD (Orthopedics)',
    active_conditions_count: 3,
    last_visit_date: '2026-08-14',
  },
  {
    patient_id: 'MEM-331092',
    name: 'Marcus Brody',
    birth_date: '1981-11-04',
    gender: 'male',
    mrn: 'MRN-551029',
    primary_physician: 'Dr. David Hayes, MD (Physical Medicine)',
    active_conditions_count: 2,
    last_visit_date: '2026-08-16',
  },
  {
    patient_id: 'MEM-774019',
    name: 'Samantha Reed',
    birth_date: '1992-06-21',
    gender: 'female',
    mrn: 'MRN-994812',
    primary_physician: 'Dr. Angela Rossi, MD (Neurology)',
    active_conditions_count: 4,
    last_visit_date: '2026-08-17',
  },
  {
    patient_id: 'MEM-602914',
    name: 'Johnathan Hayes',
    birth_date: '1968-09-29',
    gender: 'male',
    mrn: 'MRN-334190',
    primary_physician: 'Dr. Sarah Lin, MD (Orthopedics)',
    active_conditions_count: 2,
    last_visit_date: '2026-08-10',
  },
  {
    patient_id: 'MEM-119384',
    name: 'Maria Hernandez',
    birth_date: '1988-02-17',
    gender: 'female',
    mrn: 'MRN-221948',
    primary_physician: 'Dr. Robert Martinez, MD (Internal Medicine)',
    active_conditions_count: 1,
    last_visit_date: '2026-08-05',
  },
];

export const MOCK_FULL_PATIENTS: Record<string, PatientFullRecord> = {
  'MEM-948201': {
    patient_id: 'MEM-948201',
    demographics: {
      fullName: 'Eleanor Vance',
      birthDate: '1974-03-12',
      gender: 'Female',
      phone: '(555) 392-8819',
      email: 'eleanor.vance@example.com',
      address: '742 Evergreen Terrace, Springfield, OR',
      insurancePayer: 'Medicare Part B / Noridian MAC J-F',
      memberId: 'MEM-948201',
      groupNumber: 'GRP-9921-MED',
      primaryCareDoctor: 'Dr. Sarah Lin, MD (Orthopedic Spine)',
    },
    vitals: {
      bloodPressure: '124/82 mmHg',
      heartRate: 72,
      height: '5 ft 6 in (168 cm)',
      weight: '148 lbs (67.1 kg)',
      bmi: 23.9,
      recordedDate: '2026-08-14',
    },
    conditions: [
      { code: 'M54.16', name: 'Radiculopathy, lumbar region (L4-L5 left)', onsetDate: '2026-04-10', clinicalStatus: 'active', verificationStatus: 'confirmed' },
      { code: 'M51.26', name: 'Other intervertebral disc displacement, lumbar region', onsetDate: '2026-04-10', clinicalStatus: 'active', verificationStatus: 'confirmed' },
      { code: 'M54.50', name: 'Low back pain, unspecified', onsetDate: '2025-10-18', clinicalStatus: 'active', verificationStatus: 'confirmed' },
    ],
    medications: [
      { id: 'MED-1', name: 'Meloxicam', dosage: '15 mg', frequency: 'Oral daily', startDate: '2026-05-01', status: 'active', prescriber: 'Dr. Sarah Lin' },
      { id: 'MED-2', name: 'Gabapentin', dosage: '300 mg', frequency: 'TID oral', startDate: '2026-06-15', status: 'active', prescriber: 'Dr. Sarah Lin' },
      { id: 'MED-3', name: 'Cyclobenzaprine', dosage: '10 mg', frequency: 'Nightly PRN', startDate: '2026-05-10', endDate: '2026-06-30', status: 'completed', prescriber: 'Dr. Sarah Lin' },
    ],
    imagingHistory: [
      {
        id: 'IMG-XRAY-01',
        modality: 'X-Ray',
        bodyPart: 'Lumbar Spine (2 Views AP / Lateral)',
        studyDate: '2026-05-02',
        accessionNumber: 'ACC-2026-8819',
        status: 'final',
        findings: 'Mild intervertebral disc space narrowing at L4-L5 and L5-S1. No acute fractures or spondylolisthesis. Vertebral heights preserved.',
        impression: '1. Moderate degenerative disc disease L4-L5.\n2. Recommend clinical correlation for left radicular symptoms.',
      },
    ],
    conservativeCareHistory: [
      {
        id: 'PT-01',
        therapyType: 'Physical Therapy',
        startDate: '2026-05-15',
        endDate: '2026-07-10',
        weeksCompleted: 8,
        sessionsCompleted: 16,
        outcome: 'Partial improvement',
        provider: 'Peak Motion Physical Therapy (Dr. Todd Jenkins, DPT)',
        notes: 'Completed 16 sessions of core stabilization, pelvic tilts, and lumbar decompression. Persistent left L5 dermatomal pain rated 6/10 on NRS.',
      },
      {
        id: 'PT-02',
        therapyType: 'NSAID Regimen',
        startDate: '2026-05-01',
        weeksCompleted: 10,
        sessionsCompleted: 70,
        outcome: 'Partial improvement',
        provider: 'Dr. Sarah Lin, MD',
        notes: 'Trialed full-dose oral Meloxicam 15mg QD with minimal relief of neuropathic radiating leg symptoms.',
      },
    ],
    clinicalNotes: [
      {
        id: 'NOTE-01',
        date: '2026-08-14',
        author: 'Dr. Sarah Lin, MD',
        authorRole: 'Attending Orthopedic Surgeon',
        noteType: 'Progress Note',
        text: 'Patient returns for follow-up of refractory left lower extremity radicular pain in L5 distribution. Has completed 8 weeks of formal physical therapy (Peak Motion) and 10 weeks of prescription NSAIDs + Gabapentin without durable symptom resolution. Physical examination demonstrates positive Straight Leg Raise on left at 45 degrees, decreased left patellar and Achilles reflexes (1+), and 4/5 left great toe extensor weakness. Lumbar X-rays from 2026-05-02 demonstrated L4-L5 disc narrowing. No red flags (no saddle anesthesia, normal bowel/bladder function). Requesting Lumbar MRI without contrast (CPT 72148) to evaluate for disc herniation and surgical planning.',
      },
    ],
    allergies: ['Penicillin (Hives)', 'Sulfa Drugs (Nausea)'],
  },
  'MEM-331092': {
    patient_id: 'MEM-331092',
    demographics: {
      fullName: 'Marcus Brody',
      birthDate: '1981-11-04',
      gender: 'Male',
      phone: '(555) 782-9901',
      email: 'mbrody@example.com',
      address: '124 College Avenue, Boston, MA',
      insurancePayer: 'Blue Cross Commercial / NGS Jurisdiction K',
      memberId: 'MEM-331092',
      groupNumber: 'BCBS-8820',
      primaryCareDoctor: 'Dr. David Hayes, MD',
    },
    vitals: {
      bloodPressure: '132/86 mmHg',
      heartRate: 78,
      height: '6 ft 1 in (185 cm)',
      weight: '210 lbs (95.2 kg)',
      bmi: 27.7,
      recordedDate: '2026-08-16',
    },
    conditions: [
      { code: 'M54.50', name: 'Low back pain, acute non-specific', onsetDate: '2026-08-08', clinicalStatus: 'active', verificationStatus: 'confirmed' },
    ],
    medications: [
      { id: 'MED-10', name: 'Ibuprofen', dosage: '600 mg', frequency: 'TID PRN', startDate: '2026-08-09', status: 'active', prescriber: 'Dr. David Hayes' },
    ],
    imagingHistory: [],
    conservativeCareHistory: [
      {
        id: 'PT-10',
        therapyType: 'NSAID Regimen',
        startDate: '2026-08-09',
        weeksCompleted: 1,
        sessionsCompleted: 7,
        outcome: 'No improvement',
        provider: 'Dr. David Hayes, MD',
        notes: '1 week of over-the-counter NSAIDs after lifting injury.',
      },
    ],
    clinicalNotes: [
      {
        id: 'NOTE-10',
        date: '2026-08-16',
        author: 'Dr. David Hayes, MD',
        authorRole: 'Primary Care Physician',
        noteType: 'Initial Evaluation',
        text: 'Patient reports sudden onset lower back pain 8 days ago after moving heavy furniture. Pain is axial with no radiating leg pain. No neurological deficits on exam (negative SLR, 5/5 motor strength throughout). Has taken Ibuprofen for 1 week. Requesting Lumbar MRI.',
      },
    ],
    allergies: ['None known'],
  },
  'MEM-774019': {
    patient_id: 'MEM-774019',
    demographics: {
      fullName: 'Samantha Reed',
      birthDate: '1992-06-21',
      gender: 'Female',
      phone: '(555) 441-2093',
      email: 's.reed@example.com',
      address: '89 Willow Creek Road, Seattle, WA',
      insurancePayer: 'Medicare Advantage Part C / Noridian MAC J-F',
      memberId: 'MEM-774019',
      groupNumber: 'ADV-7718',
      primaryCareDoctor: 'Dr. Angela Rossi, MD',
    },
    vitals: {
      bloodPressure: '118/76 mmHg',
      heartRate: 84,
      height: '5 ft 4 in (163 cm)',
      weight: '130 lbs (59.0 kg)',
      bmi: 22.3,
      recordedDate: '2026-08-17',
    },
    conditions: [
      { code: 'G83.4', name: 'Cauda equina syndrome with saddle anesthesia', onsetDate: '2026-08-16', clinicalStatus: 'active', verificationStatus: 'provisional' },
      { code: 'R33.9', name: 'Retention of urine, unspecified', onsetDate: '2026-08-16', clinicalStatus: 'active', verificationStatus: 'confirmed' },
    ],
    medications: [],
    imagingHistory: [],
    conservativeCareHistory: [],
    clinicalNotes: [
      {
        id: 'NOTE-20',
        date: '2026-08-17',
        author: 'Dr. Angela Rossi, MD',
        authorRole: 'Emergency Medicine / Neurology',
        noteType: 'Urgent Consult',
        text: 'EMERGENCY: Patient presents with acute urinary retention (post-void bladder scan > 650cc), profound bilateral lower extremity weakness (3/5 dorsiflexion), and numbness in the perineal/saddle region following severe back pain. Suspected Cauda Equina Syndrome. STAT Lumbar MRI requested without waiting for conservative care.',
      },
    ],
    allergies: ['Latex (Severe)'],
  },
};

export const MOCK_POLICIES: CMSPolicyItem[] = [
  {
    id: 'LCD-34220',
    type: 'LCD',
    policyNumber: 'LCD L34220',
    title: 'Magnetic Resonance Imaging (MRI) of the Lumbar Spine',
    jurisdiction: 'Jurisdiction J-F & J-K (Noridian / NGS)',
    effectiveDate: '2024-01-01',
    lastRevisedDate: '2026-01-15',
    cptCodes: ['72148', '72149', '72158'],
    coveredIcd10Codes: ['M54.16', 'M54.17', 'M51.26', 'M51.27', 'G83.4', 'M54.41', 'M54.42'],
    summary: 'Establishes medical necessity coverage criteria for diagnostic Lumbar Spine MRI in Medicare beneficiaries.',
    criteriaRequirements: [
      {
        id: 'LCD-34220-C1',
        section: 'Section B.1 - Conservative Therapy',
        requirement: 'Documented completion of at least six (6) consecutive weeks of conservative non-operative treatment (e.g. physical therapy, chiropractic, NSAIDs) within the preceding 6 months, unless emergency red flags are present.',
        mandatory: true,
        evidenceNeeded: 'PT clinic notes, dates, and physician clinical notes documenting lack of response.',
      },
      {
        id: 'LCD-34220-C2',
        section: 'Section B.2 - Initial Imaging Corroboration',
        requirement: 'Prior plain radiographs (lumbar X-rays) must be performed prior to advanced cross-sectional MRI imaging to rule out gross structural pathology, instability, or fracture.',
        mandatory: true,
        evidenceNeeded: 'X-ray report accession number, date of study, and summary of findings.',
      },
      {
        id: 'LCD-34220-C3',
        section: 'Section B.3 - Neurological Deficit',
        requirement: 'Documentation of objective motor, sensory, or reflex neurological deficit corresponding to lumbar nerve root distribution (radiculopathy or positive straight leg raise).',
        mandatory: true,
        evidenceNeeded: 'Documented physical exam finding (SLR degrees, reflex score 0-4+, or myotomal weakness).',
      },
      {
        id: 'LCD-34220-C4',
        section: 'Section B.4 - Red Flag Exception Clause',
        requirement: 'In the presence of progressive neurologic emergency red flags (cauda equina syndrome, acute bowel/bladder dysfunction, saddle anesthesia, rapid motor loss), the 6-week conservative care rule is waived for STAT review.',
        mandatory: true,
        evidenceNeeded: 'Explicit clinical emergency documentation.',
      },
    ],
  },
  {
    id: 'ART-57206',
    type: 'Article',
    policyNumber: 'Billing and Coding: Article A57206',
    title: 'Coverage Guidance: Lumbar Spine Advanced Diagnostic Modalities',
    jurisdiction: 'CMS National Guidance',
    effectiveDate: '2023-10-01',
    cptCodes: ['72148', '72149', '72158'],
    coveredIcd10Codes: ['M54.16', 'M51.26', 'G83.4'],
    summary: 'Billing and clinical diagnostic crosswalk for Lumbar MRI non-contrast procedures.',
    criteriaRequirements: [
      {
        id: 'ART-57206-C1',
        section: 'Section 3 - ICD-10 Specificity',
        requirement: 'Primary diagnosis code must represent anatomically specific radiculopathy, disc displacement, or stenosis (non-specific low back pain M54.50 requires documented failure of comprehensive conservative care).',
        mandatory: true,
        evidenceNeeded: 'ICD-10-CM 5-to-6 character diagnosis code.',
      },
    ],
  },
];

export const MOCK_PA_CASES: CaseSummary[] = [
  {
    case_id: 'PA-2026-0819-01',
    patient_id: 'MEM-948201',
    patient_name: 'Eleanor Vance',
    cpt_code: '72148',
    cpt_description: 'MRI Lumbar Spine without Contrast',
    icd10_code: 'M54.16',
    icd10_description: 'Radiculopathy, lumbar region',
    status: 'approved',
    outcome: 'APPROVE',
    created_at: '2026-08-17T10:14:00Z',
    tracking_code: 'PA-2026-MRI-9482',
    urgency: 'standard',
    sla_deadline: '2026-08-20T10:14:00Z',
  },
  {
    case_id: 'PA-2026-0819-02',
    patient_id: 'MEM-331092',
    patient_name: 'Marcus Brody',
    cpt_code: '72148',
    cpt_description: 'MRI Lumbar Spine without Contrast',
    icd10_code: 'M54.50',
    icd10_description: 'Low back pain, unspecified',
    status: 'rfi_requested',
    outcome: 'REQUEST_INFO',
    created_at: '2026-08-18T08:30:00Z',
    tracking_code: 'PA-2026-MRI-3310',
    urgency: 'standard',
    sla_deadline: '2026-08-21T08:30:00Z',
    rfi_question: 'Reviewer requested documentation of 6 weeks of conservative therapy and prior lumbar plain radiograph (X-Ray) report per LCD L34220.',
    rfi_requested_at: '2026-08-18T14:20:00Z',
  },
  {
    case_id: 'PA-2026-0819-03',
    patient_id: 'MEM-774019',
    patient_name: 'Samantha Reed',
    cpt_code: '72148',
    cpt_description: 'MRI Lumbar Spine without Contrast',
    icd10_code: 'G83.4',
    icd10_description: 'Cauda equina syndrome',
    status: 'pending_review',
    outcome: 'PEND',
    created_at: '2026-08-18T15:45:00Z',
    tracking_code: 'PA-2026-MRI-7740',
    urgency: 'stat',
    sla_deadline: '2026-08-18T19:45:00Z',
  },
  {
    case_id: 'PA-2026-0819-04',
    patient_id: 'MEM-602914',
    patient_name: 'Johnathan Hayes',
    cpt_code: '73721',
    cpt_description: 'MRI Knee Joint without Contrast',
    icd10_code: 'M23.22',
    icd10_description: 'Derangement of meniscus',
    status: 'in_review',
    outcome: null,
    created_at: '2026-08-18T16:00:00Z',
    tracking_code: 'PA-2026-MRI-6029',
    urgency: 'standard',
    sla_deadline: '2026-08-21T16:00:00Z',
  },
];
