import { CaseSummary, CaseDetail } from '../types/reviewer';
import { CMSAuditEvent } from '../types/audit';
import { PolicyKnowledgeGraph, CMSPolicySyncStats } from '../types/policyGraph';
import { SystemMetrics } from '../types/observability';

export const MOCK_REVIEW_QUEUE_CASES: CaseSummary[] = [
  {
    case_id: 'PA-2026-0819-03',
    patient_id: 'MEM-774019',
    patient_name: 'Samantha Reed',
    cpt_code: '72148',
    cpt_description: 'MRI Lumbar Spine without Contrast',
    icd10_code: 'G83.4',
    icd10_description: 'Cauda equina syndrome with saddle anesthesia',
    status: 'pending_review',
    outcome: 'PEND',
    created_at: '2026-08-18T15:45:00Z',
    priority_score: 98,
    urgency: 'stat',
    sla_deadline: '2026-08-18T19:45:00Z',
    red_flags_present: true,
  },
  {
    case_id: 'PA-2026-0819-02',
    patient_id: 'MEM-331092',
    patient_name: 'Marcus Brody',
    cpt_code: '72148',
    cpt_description: 'MRI Lumbar Spine without Contrast',
    icd10_code: 'M54.50',
    icd10_description: 'Low back pain, unspecified',
    status: 'rfi_requested',
    outcome: 'REQUEST_INFO',
    created_at: '2026-08-18T08:30:00Z',
    priority_score: 65,
    urgency: 'standard',
    sla_deadline: '2026-08-21T08:30:00Z',
    red_flags_present: false,
  },
  {
    case_id: 'PA-2026-0819-04',
    patient_id: 'MEM-602914',
    patient_name: 'Johnathan Hayes',
    cpt_code: '73721',
    cpt_description: 'MRI Knee Joint without Contrast',
    icd10_code: 'M23.22',
    icd10_description: 'Derangement of meniscus, tear of posterior horn',
    status: 'in_review',
    outcome: 'PEND',
    created_at: '2026-08-18T16:00:00Z',
    priority_score: 72,
    urgency: 'standard',
    sla_deadline: '2026-08-21T16:00:00Z',
    red_flags_present: false,
  },
  {
    case_id: 'PA-2026-0819-01',
    patient_id: 'MEM-948201',
    patient_name: 'Eleanor Vance',
    cpt_code: '72148',
    cpt_description: 'MRI Lumbar Spine without Contrast',
    icd10_code: 'M54.16',
    icd10_description: 'Radiculopathy, lumbar region (L4/L5)',
    status: 'approved',
    outcome: 'APPROVE',
    created_at: '2026-08-17T10:14:00Z',
    priority_score: 40,
    urgency: 'standard',
    sla_deadline: '2026-08-20T10:14:00Z',
    red_flags_present: false,
  },
];

export const MOCK_CASE_DETAILS: Record<string, CaseDetail> = {
  'PA-2026-0819-03': {
    case_id: 'PA-2026-0819-03',
    patient_id: 'MEM-774019',
    patient_name: 'Samantha Reed (Female, 34)',
    cpt_code: '72148',
    cpt_description: 'MRI Lumbar Spine without Contrast',
    icd10_code: 'G83.4',
    icd10_description: 'Cauda equina syndrome with saddle anesthesia',
    status: 'pending_review',
    outcome: 'PEND',
    created_at: '2026-08-18T15:45:00Z',
    priority_score: 98,
    urgency: 'stat',
    sla_deadline: '2026-08-18T19:45:00Z',
    red_flags_present: true,
    evaluated_at: '2026-08-18T15:45:12Z',
    evaluator_version: 'CMS-Deterministic-Rules-v4.2',
    ai_confidence_score: 0.96,
    readiness_percentage: 95,
    message: 'CRITICAL ALERT: Emergency red flags present (acute cauda equina syndrome). Conservative 6-week therapy trial is WAIVED per LCD L34220 Section B.4. Routed for STAT Medical Director sign-off.',
    criteria: [
      {
        criterion_id: 'LCD-34220-C1',
        description: '6 weeks conservative care requirement',
        status: 'NOT_APPLICABLE',
        evidence_summary: 'Waived per emergency exception clause (acute neuro deficit).',
        policy_reference: 'LCD L34220 Section B.1 Exception',
        is_critical: true,
      },
      {
        criterion_id: 'LCD-34220-C2',
        description: 'Prior plain lumbar radiograph (X-Ray)',
        status: 'SATISFIED',
        evidence_summary: 'Waived / deferred for acute emergency decompression evaluation.',
        policy_reference: 'LCD L34220 Section B.2',
      },
      {
        criterion_id: 'LCD-34220-C3',
        description: 'Objective neurological examination deficit',
        status: 'SATISFIED',
        evidence_summary: 'Profound bilateral lower extremity weakness (3/5 dorsiflexion), saddle anesthesia, urinary retention (>650cc post-void).',
        policy_reference: 'Article A57206 Section 3',
        is_critical: true,
      },
      {
        criterion_id: 'LCD-34220-C4',
        description: 'Emergency Red Flag Protocol Evaluation',
        status: 'SATISFIED',
        evidence_summary: 'Cauda Equina Syndrome confirmed on emergency physical exam.',
        policy_reference: 'LCD L34220 Section B.4',
        is_critical: true,
      },
    ],
    policy_refs: [
      {
        lcd_id: 'LCD-34220',
        lcd_title: 'Magnetic Resonance Imaging of the Lumbar Spine',
        article_id: 'ART-57206',
        cpt_code: '72148',
        section: 'Section B.4 Red Flag Emergency Clause',
      },
    ],
    clinical_evidence: {
      diagnosis_icd10: 'G83.4',
      conservative_therapy_weeks: 0,
      conservative_therapy_types: [],
      prior_lumbar_imaging: false,
      neurological_symptoms: true,
      neurological_exam_documented: true,
      red_flags_present: true,
      red_flag_details: ['Cauda equina syndrome', 'Acute urinary retention', 'Perineal saddle anesthesia'],
      clinical_notes: [
        'EMERGENCY CONSULT (Dr. Angela Rossi, MD): 34yo female presents to ED with 12 hours of progressive lower extremity weakness, bilateral foot drop (3/5), loss of sensation in S2-S5 dermatomes (saddle distribution), and urinary retention with bladder scan > 650cc. Urgent decompressive MRI Lumbar Spine requested STAT.',
      ],
    },
    attached_documents: [
      {
        id: 'DOC-991',
        name: 'ED_Urgent_Neuro_Consult_Note.pdf',
        type: 'Emergency Consultation',
        uploaded_at: '2026-08-18T15:45:00Z',
        ocr_snippet: 'Primary impression: Acute Cauda Equina Syndrome secondary to massive disc herniation.',
      },
      {
        id: 'DOC-992',
        name: 'Bladder_Scan_Urinary_Retention_Log.pdf',
        type: 'Diagnostic Measurement',
        uploaded_at: '2026-08-18T15:45:00Z',
        ocr_snippet: 'Post-void residual volume measured at 685 mL.',
      },
    ],
    fhir_bundle_summary: {
      patient_id: 'MEM-774019',
      encounter_date: '2026-08-18',
      diagnoses: ['G83.4 (Cauda equina syndrome)', 'R33.9 (Urinary retention)'],
      medications: ['Dexamethasone 10mg IV STAT'],
    },
  },
  'PA-2026-0819-02': {
    case_id: 'PA-2026-0819-02',
    patient_id: 'MEM-331092',
    patient_name: 'Marcus Brody (Male, 44)',
    cpt_code: '72148',
    cpt_description: 'MRI Lumbar Spine without Contrast',
    icd10_code: 'M54.50',
    icd10_description: 'Low back pain, unspecified',
    status: 'rfi_requested',
    outcome: 'REQUEST_INFO',
    created_at: '2026-08-18T08:30:00Z',
    priority_score: 65,
    urgency: 'standard',
    sla_deadline: '2026-08-21T08:30:00Z',
    red_flags_present: false,
    evaluated_at: '2026-08-18T08:30:15Z',
    evaluator_version: 'CMS-Deterministic-Rules-v4.2',
    ai_confidence_score: 0.88,
    readiness_percentage: 40,
    message: 'Coverage criteria unmet. Patient has only completed 1 week of conservative care (6 weeks required) and no prior lumbar plain radiograph (X-Ray) is documented in the EHR.',
    criteria: [
      {
        criterion_id: 'LCD-34220-C1',
        description: '6 weeks conservative care requirement',
        status: 'NOT_SATISFIED',
        evidence_summary: 'Only 1 week of rest/OTC Ibuprofen documented; minimum 6 weeks supervised PT required.',
        policy_reference: 'LCD L34220 Section B.1',
        is_critical: true,
      },
      {
        criterion_id: 'LCD-34220-C2',
        description: 'Prior plain lumbar radiograph (X-Ray)',
        status: 'NOT_SATISFIED',
        evidence_summary: 'No plain radiograph performed or uploaded.',
        policy_reference: 'LCD L34220 Section B.2',
      },
      {
        criterion_id: 'LCD-34220-C3',
        description: 'Objective neurological examination deficit',
        status: 'UNKNOWN',
        evidence_summary: 'Exam notes show normal motor/reflexes and negative straight leg raise.',
        policy_reference: 'Article A57206 Section 3',
      },
      {
        criterion_id: 'LCD-34220-C4',
        description: 'Emergency Red Flag Protocol Evaluation',
        status: 'SATISFIED',
        evidence_summary: 'No emergency red flags present (routine authorization rules apply).',
        policy_reference: 'LCD L34220 Section B.4',
        is_critical: true,
      },
    ],
    policy_refs: [
      {
        lcd_id: 'LCD-34220',
        lcd_title: 'Magnetic Resonance Imaging of the Lumbar Spine',
        article_id: 'ART-57206',
        cpt_code: '72148',
      },
    ],
    clinical_evidence: {
      diagnosis_icd10: 'M54.50',
      conservative_therapy_weeks: 1,
      conservative_therapy_types: ['Rest', 'OTC Ibuprofen'],
      prior_lumbar_imaging: false,
      neurological_symptoms: false,
      neurological_exam_documented: true,
      red_flags_present: false,
      clinical_notes: [
        'PCP Progress Note: Patient has 8 days of axial low back pain after lifting furniture. 5/5 strength throughout, negative SLR. Advised 6 weeks physical therapy and lumbar X-ray.',
      ],
    },
    attached_documents: [
      {
        id: 'DOC-881',
        name: 'PrimaryCare_Initial_Encounter.pdf',
        type: 'Clinic Progress Note',
        uploaded_at: '2026-08-18T08:30:00Z',
        ocr_snippet: 'Onset 8 days prior. Conservative trial 1 week duration.',
      },
    ],
  },
  'PA-2026-0819-01': {
    case_id: 'PA-2026-0819-01',
    patient_id: 'MEM-948201',
    patient_name: 'Eleanor Vance (Female, 52)',
    cpt_code: '72148',
    cpt_description: 'MRI Lumbar Spine without Contrast',
    icd10_code: 'M54.16',
    icd10_description: 'Radiculopathy, lumbar region (L4/L5)',
    status: 'approved',
    outcome: 'APPROVE',
    created_at: '2026-08-17T10:14:00Z',
    priority_score: 40,
    urgency: 'standard',
    sla_deadline: '2026-08-20T10:14:00Z',
    red_flags_present: false,
    evaluated_at: '2026-08-17T10:14:08Z',
    evaluator_version: 'CMS-Deterministic-Rules-v4.2',
    ai_confidence_score: 0.99,
    readiness_percentage: 100,
    message: 'Full coverage criteria satisfied. 8 weeks completed PT documented at Peak Motion, corroborated by plain lumbar radiographs from 2026-05-02 and documented L5 radiculopathy.',
    criteria: [
      {
        criterion_id: 'LCD-34220-C1',
        description: '6 weeks conservative care requirement',
        status: 'SATISFIED',
        evidence_summary: '8 weeks formal physical therapy + Meloxicam documented.',
        policy_reference: 'LCD L34220 Section B.1',
        is_critical: true,
      },
      {
        criterion_id: 'LCD-34220-C2',
        description: 'Prior plain lumbar radiograph (X-Ray)',
        status: 'SATISFIED',
        evidence_summary: 'Lumbar spine 2-view plain films performed 2026-05-02 (ACC-2026-8819).',
        policy_reference: 'LCD L34220 Section B.2',
      },
      {
        criterion_id: 'LCD-34220-C3',
        description: 'Objective neurological examination deficit',
        status: 'SATISFIED',
        evidence_summary: 'Positive left straight leg raise at 45 deg, reduced patellar/Achilles reflexes (1+), 4/5 EHL weakness.',
        policy_reference: 'Article A57206 Section 3',
        is_critical: true,
      },
      {
        criterion_id: 'LCD-34220-C4',
        description: 'Emergency Red Flag Protocol Evaluation',
        status: 'SATISFIED',
        evidence_summary: 'No red flags present.',
        policy_reference: 'LCD L34220 Section B.4',
        is_critical: true,
      },
    ],
    policy_refs: [
      {
        lcd_id: 'LCD-34220',
        lcd_title: 'Magnetic Resonance Imaging of the Lumbar Spine',
        article_id: 'ART-57206',
        cpt_code: '72148',
      },
    ],
    clinical_evidence: {
      diagnosis_icd10: 'M54.16',
      conservative_therapy_weeks: 8,
      conservative_therapy_types: ['Physical therapy', 'NSAIDs', 'Gabapentin'],
      prior_lumbar_imaging: true,
      prior_imaging_date: '2026-05-02',
      neurological_symptoms: true,
      neurological_exam_documented: true,
      red_flags_present: false,
      clinical_notes: [
        'Orthopedic Clinic Note: Patient with 3-month history of severe left L5 dermatomal pain. Completed 16 sessions of PT at Peak Motion. Prior X-rays show L4-L5 disc space loss. Positive SLR left 45 deg.',
      ],
    },
    attached_documents: [
      {
        id: 'DOC-101',
        name: 'Peak_Motion_PT_16Sessions_Discharge.pdf',
        type: 'Physical Therapy Record',
        uploaded_at: '2026-08-17T10:14:00Z',
        ocr_snippet: 'Completed 16 sessions of core stabilization and traction. Pain continues at 6/10.',
      },
      {
        id: 'DOC-102',
        name: 'Lumbar_Spine_XRay_Report_20260502.pdf',
        type: 'Radiology Report',
        uploaded_at: '2026-08-17T10:14:00Z',
        ocr_snippet: 'Impression: Moderate disc height narrowing L4-L5 and L5-S1.',
      },
    ],
  },
};

export const MOCK_AUDIT_EVENTS: CMSAuditEvent[] = [
  {
    id: 'EVT-2026-00918',
    case_id: 'PA-2026-0819-03',
    event_timestamp: '2026-08-18T15:45:00Z',
    event_type: 'INITIAL_INTAKE',
    patient_id: 'MEM-774019',
    procedure_code: '72148',
    diagnosis_codes: ['G83.4', 'R33.9'],
    policy_id: 'LCD-34220',
    policy_version_number: 4,
    policy_effective_date: '2024-01-01',
    rules_engine_version: 'CMS-Deterministic-Rules-v4.2',
    ai_model_version: 'groq-llama-3-70b-v2.1',
    recommendation: 'PEND',
    confidence_score: '0.96',
    criteria_results: {
      'LCD-34220-C1': 'NOT_APPLICABLE',
      'LCD-34220-C2': 'SATISFIED',
      'LCD-34220-C3': 'SATISFIED',
      'LCD-34220-C4': 'SATISFIED',
    },
    missing_evidence: {},
    audit_hash: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
    verified: true,
  },
  {
    id: 'EVT-2026-00919',
    case_id: 'PA-2026-0819-03',
    event_timestamp: '2026-08-18T15:45:12Z',
    event_type: 'EVALUATION',
    patient_id: 'MEM-774019',
    procedure_code: '72148',
    diagnosis_codes: ['G83.4'],
    policy_id: 'LCD-34220',
    policy_version_number: 4,
    rules_engine_version: 'CMS-Deterministic-Rules-v4.2',
    recommendation: 'PEND',
    confidence_score: '0.96',
    criteria_results: {
      emergency_red_flag_detected: true,
      cauda_equina_syndrome: true,
      conservative_therapy_waived: true,
    },
    audit_hash: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
    verified: true,
  },
  {
    id: 'EVT-2026-00840',
    case_id: 'PA-2026-0819-01',
    event_timestamp: '2026-08-17T10:14:08Z',
    event_type: 'DETERMINATION_ISSUED',
    patient_id: 'MEM-948201',
    procedure_code: '72148',
    diagnosis_codes: ['M54.16'],
    policy_id: 'LCD-34220',
    policy_version_number: 4,
    rules_engine_version: 'CMS-Deterministic-Rules-v4.2',
    recommendation: 'APPROVE',
    confidence_score: '0.99',
    criteria_results: {
      conservative_therapy_met: true,
      prior_xray_met: true,
      neurologic_deficit_met: true,
    },
    audit_hash: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
    verified: true,
  },
];

export const MOCK_POLICY_GRAPH: PolicyKnowledgeGraph = {
  activeLcdCount: 14,
  activeArticlesCount: 28,
  updatedAt: '2026-08-18T12:00:00Z',
  nodes: [
    { id: 'cpt-72148', label: 'CPT 72148 (Lumbar MRI w/o)', type: 'CPT', category: 'Radiology' },
    { id: 'lcd-34220', label: 'LCD L34220 (Lumbar MRI Policy)', type: 'LCD', category: 'Noridian J-F' },
    { id: 'art-57206', label: 'Article A57206 (Billing Guidance)', type: 'ARTICLE', category: 'CMS Article' },
    { id: 'crit-pt6wk', label: 'Req: 6 Weeks Conservative Care', type: 'CRITERIA', category: 'Medical Necessity' },
    { id: 'crit-xray', label: 'Req: Prior Lumbar Plain Radiograph', type: 'CRITERIA', category: 'Diagnostic Prerequisite' },
    { id: 'crit-neuro', label: 'Req: Objective Radiculopathy Exam', type: 'CRITERIA', category: 'Clinical Finding' },
    { id: 'crit-redflag', label: 'Exception: Emergency Red Flag', type: 'CRITERIA', category: 'Emergency Exemption' },
    { id: 'out-approve', label: 'Deterministic APPROVE', type: 'OUTCOME', category: 'Coverage Standard' },
    { id: 'out-pend', label: 'Deterministic PEND / Review', type: 'OUTCOME', category: 'Clinical Triage' },
    { id: 'out-rfi', label: 'Deterministic REQUEST_INFO', type: 'OUTCOME', category: 'RFI Pending' },
  ],
  edges: [
    { id: 'e1', source: 'cpt-72148', target: 'lcd-34220', label: 'Governed By', type: 'maps_to' },
    { id: 'e2', source: 'lcd-34220', target: 'art-57206', label: 'Referenced By', type: 'maps_to' },
    { id: 'e3', source: 'lcd-34220', target: 'crit-pt6wk', label: 'Enforces', type: 'requires' },
    { id: 'e4', source: 'lcd-34220', target: 'crit-xray', label: 'Enforces', type: 'requires' },
    { id: 'e5', source: 'lcd-34220', target: 'crit-neuro', label: 'Enforces', type: 'requires' },
    { id: 'e6', source: 'lcd-34220', target: 'crit-redflag', label: 'Exemption Clause', type: 'requires' },
    { id: 'e7', source: 'crit-pt6wk', target: 'out-approve', label: 'All Met ->', type: 'satisfies' },
    { id: 'e8', source: 'crit-redflag', target: 'out-pend', label: 'STAT ->', type: 'triggers' },
  ],
};

export const MOCK_POLICY_SYNC_STATS: CMSPolicySyncStats = {
  lcds: 14,
  articles: 28,
  document_versions: 42,
  policy_chunks: 384,
  chunks_with_embeddings: 384,
  last_sync_timestamp: '2026-08-18T04:00:00Z',
  recent_versions: [
    { document_id: 'LCD-L34220', document_type: 'LCD', version: 4, status: 'active', created_at: '2026-01-15T00:00:00Z' },
    { document_id: 'ART-A57206', document_type: 'Article', version: 3, status: 'active', created_at: '2025-10-01T00:00:00Z' },
    { document_id: 'LCD-L33796', document_type: 'LCD', version: 2, status: 'active', created_at: '2025-08-12T00:00:00Z' },
  ],
};

export const MOCK_OBSERVABILITY_METRICS: SystemMetrics = {
  totalCasesProcessed: 1482,
  autoApprovalRate: 76.4,
  rfiRate: 14.2,
  denialRate: 4.8,
  manualReviewRate: 4.6,
  avgTurnaroundHours: 3.8,
  slaComplianceRate: 99.4,
  aiExtractionAvgLatencyMs: 1680,
  deterministicRuleLatencyMs: 38,
  dailyThroughput: [
    { date: '08/12', approved: 84, pended: 6, rfi: 14, denied: 4 },
    { date: '08/13', approved: 92, pended: 4, rfi: 18, denied: 5 },
    { date: '08/14', approved: 78, pended: 7, rfi: 12, denied: 3 },
    { date: '08/15', approved: 104, pended: 5, rfi: 15, denied: 6 },
    { date: '08/16', approved: 96, pended: 3, rfi: 16, denied: 4 },
    { date: '08/17', approved: 110, pended: 6, rfi: 19, denied: 5 },
    { date: '08/18', approved: 88, pended: 4, rfi: 13, denied: 3 },
  ],
  topCptDistribution: [
    { cpt: '72148', name: 'MRI Lumbar Spine w/o Contrast', volume: 642, passRate: 79.2 },
    { cpt: '73721', name: 'MRI Lower Extremity Knee', volume: 384, passRate: 74.8 },
    { cpt: '72149', name: 'MRI Lumbar Spine with Contrast', volume: 188, passRate: 68.4 },
    { cpt: '70551', name: 'MRI Brain without Contrast', volume: 146, passRate: 82.1 },
    { cpt: '72158', name: 'MRI Lumbar Spine w/ & w/o Contrast', volume: 122, passRate: 71.3 },
  ],
  reviewerOverrideStats: {
    totalOverrides: 68,
    concurredCount: 54,
    overriddenToApprove: 11,
    overriddenToDeny: 3,
  },
};
